# -*- coding: utf-8 -*-
import json
import os
import urllib
import urllib.parse

from helpers.csp_helper import append_csp_data, default_csp_result_object
from helpers.data_helper import append_domain_entry,\
    append_domain_entry_with_key, has_domain_entry_with_key
from helpers.http_header_helper import append_data_from_response_headers
from helpers.sri_helper import append_sri_data

def hostname_matches(hostname_a, hostname_b):
    """
    Compares two hostnames, treating an internationalized hostname and
    its IDNA (punycode) form as equal since browsers record the punycode
    form in the HAR while our configuration may use the unicode form.

    Parameters:
    hostname_a (str): The first hostname.
    hostname_b (str): The second hostname.

    Returns:
    bool: True if the hostnames identify the same host, False otherwise.
    """
    if hostname_a == hostname_b:
        return True
    try:
        return hostname_a.encode('idna') == hostname_b.encode('idna')
    except (UnicodeError, AttributeError):
        return False

def get_first_page_entries(har_data, origin_domain=None):
    """
    Returns the HAR entries that belong to the first page in the HAR.

    A HAR can contain more than one page, for example when a concurrent
    browsertime run ends up in the same browser session (crossed DevTools
    port) and navigates to another website mid-recording. Requests made
    by other pages must not be attributed to the website being tested.

    When origin_domain is given it is also compared against the hostname
    of the first recorded request; None is returned on mismatch as the
    recording then isn't of the tested website at all.

    Parameters:
    har_data (dict): Parsed HAR content, with or without the 'log' wrapper.
    origin_domain (str, optional): Hostname the recording is expected
    to start with.

    Returns:
    list: The entries belonging to the first page,
          or None if the recording starts with another website.
    """
    if 'log' in har_data:
        har_data = har_data['log']

    entries = har_data.get('entries', [])

    if origin_domain is not None and len(entries) > 0:
        first_url = entries[0].get('request', {}).get('url', '')
        first_hostname = urllib.parse.urlparse(first_url).hostname
        if first_hostname is not None and \
                not hostname_matches(first_hostname, origin_domain):
            return None

    pages = har_data.get('pages', [])
    if len(pages) == 0:
        return entries

    first_page_id = pages[0].get('id')
    if first_page_id is None:
        return entries

    return [entry for entry in entries
            if entry.get('pageref', first_page_id) == first_page_id]

def get_data_from_sitespeed(filename, org_domain):
    """
    Extracts data from a HAR (HTTP Archive) file generated by SiteSpeed and
    updates a result dictionary.

    This function reads a HAR file and iterates over the entries in the log.
    For each entry, it extracts information such as the request URL,
    scheme, HTTP version, and server IP address. It also appends data 
    from the response headers and MIME types.
    The extracted information is then added to the result dictionary 
    under the appropriate categories.

    Parameters:
    filename (str): The name of the HAR file to be read.
    org_domain (str): The original domain for which the HAR file was generated.

    Returns:
    dict: The result dictionary updated with the extracted information.
          The dictionary also includes a 'visits' key which is set to
          1 to indicate that the function has been called once for the given HAR file.
    """
    result = {
        'visits': 0,
        org_domain: default_csp_result_object(True)
    }

    if filename == '':
        result['failed'] = True
        return result

    if not os.path.exists(filename):
        result['failed'] = True
        return result

    # Fix for content having unallowed chars
    with open(filename, encoding='utf-8') as json_input_file:
        har_data = json.load(json_input_file)

        if 'log' in har_data:
            har_data = har_data['log']

        entries = get_first_page_entries(har_data, org_domain)

        # fail if the recording isn't of the tested website
        if entries is None:
            result['failed'] = True
            return result

        # return zero visits if no entries
        if len(entries) == 0:
            result['failed'] = True
            return result

        for entry in entries:
            req = entry['request']
            res = entry['response']
            req_url = req['url']

            o = urllib.parse.urlparse(req_url)
            req_domain = o.hostname

            if req_domain not in result:
                result[req_domain] = default_csp_result_object(False)

            append_domain_entry(req_domain, 'schemes', o.scheme.upper(), result)
            append_domain_entry(req_domain, 'urls', req_url, result)

            scheme = f'{o.scheme.lower()}:'
            if not has_domain_entry_with_key(
                    org_domain,
                    'csp-findings',
                    'scheme-sources',
                    scheme, result) and scheme != 'http:':
                append_domain_entry_with_key(
                    org_domain,
                    'csp-findings',
                    'scheme-sources',
                    scheme,
                    result)

            if 'httpVersion' in req and req['httpVersion'] != '':
                http_version = req['httpVersion'].replace('h2', 'HTTP/2')
                http_version = http_version.replace('h3', 'HTTP/3')
                http_version = http_version.upper()
                append_domain_entry(req_domain, 'protocols', http_version, result)

            if 'httpVersion' in res and res['httpVersion'] != '':
                http_version = res['httpVersion'].replace('h2', 'HTTP/2')
                http_version = http_version.replace('h3', 'HTTP/3')
                http_version = http_version.upper()
                append_domain_entry(req_domain, 'protocols', http_version, result)

            if 'serverIPAddress' in entry:
                if ':' in entry['serverIPAddress']:
                    append_domain_entry(req_domain, 'ip-versions', 'IPv6', result)
                else:
                    append_domain_entry(req_domain, 'ip-versions', 'IPv4', result)

            append_data_from_response_headers(
                res['headers'],
                req_url,
                org_domain,
                req_domain,
                result)

            append_csp_data(req_url, req_domain, res, org_domain, result)
            append_sri_data(req_domain, res, result)

    result['visits'] = 1
    return result
