name: "Regression Test - CSS Linting Test"
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**software-full.json'
      - '**software-sources.json'
      - '**update-software.yml'
      - '**update_software_helper.py'
      - '**software-rules.json'
      - 'Dockerfile'
      - '**regression-test-docker-image.yml'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                config: ['SITESPEED_USE_DOCKER=False']
                version: [27]
                include:
                  - os: ubuntu-latest
                    config: 'SITESPEED_USE_DOCKER=True'
                    version: 27
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
    - name: Java Version
      run: java -version
    - name: Setup Node.js (v4 version 20.x)
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      shell: bash
      name: Setup Google Chrome browser (ONLY used for Sitespeed)
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version
    - name: Setup npm packages
      run: npm ci --only=production
      timeout-minutes: 30
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: RUNNING TEST - LINUX (no-errors)
      run: |
         python default.py -t ${{ matrix.version }} -r -u https://webperf.se?webperf-core-test-27-no-errors -o data/testresult-${{ matrix.version }}.json --setting ${{ matrix.config }} --setting tests.sitespeed.xvfb=true --setting general.cache.use=true --setting general.cache.max-age=5256000 --setting tests.sitespeed.cache.folder=unittests
         python .github/workflows/verify_result.py -t ${{ matrix.version }}
    - if: ${{ matrix.os == 'windows-latest' }}
      name: RUNNING TEST - WINDOWS (no-errors)
      run: |
         python default.py -t ${{ matrix.version }} -r -u https://webperf.se?webperf-core-test-27-no-errors -o data\testresult-${{ matrix.version }}.json --setting ${{ matrix.config }} --setting general.cache.use=true --setting general.cache.max-age=5256000 --setting tests.sitespeed.cache.folder=unittests
         python .github\workflows\verify_result.py -t ${{ matrix.version }}
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: RUNNING TEST - LINUX (with-errors)
      run: |
         python default.py -t ${{ matrix.version }} -r -u https://webperf.se?webperf-core-test-27-with-errors -o data/testresult-${{ matrix.version }}.json --setting ${{ matrix.config }} --setting tests.sitespeed.xvfb=true --setting general.cache.use=true --setting general.cache.max-age=5256000 --setting tests.sitespeed.cache.folder=unittests
         python .github/workflows/verify_result.py -t ${{ matrix.version }}
    - if: ${{ matrix.os == 'windows-latest' }}
      name: RUNNING TEST - WINDOWS (with-errors)
      run: |
         python default.py -t ${{ matrix.version }} -r -u https://webperf.se?webperf-core-test-27-with-errors -o data\testresult-${{ matrix.version }}.json --setting ${{ matrix.config }} --setting general.cache.use=true --setting general.cache.max-age=5256000 --setting tests.sitespeed.cache.folder=unittests
         python .github\workflows\verify_result.py -t ${{ matrix.version }}
