name: "Regression Test - Software (Alpha) Test"
on: 
  push:
    paths-ignore:
      - '**.md'
      - 'software-sources.json'
      - '**update-software.yml'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                version: [25]
                config: ['review_show_improvements_only=True,sitespeed_use_docker=False']
                include:
                  - os: ubuntu-latest
                    config: 'review_show_improvements_only=True,sitespeed_use_docker=True'
                    version: 25
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
    - name: Setup Node.js (v3 version 18.x)
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      shell: bash
      name: Setup Google Chrome browser (ONLY used for Sitespeed)
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version
    - name: Setup Sitespeed.io npm package (ONLY used for Sitespeed)
      run: npm install sitespeed.io
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Setup config (using SAMPLE-config.py as config.py) - LINUX
      run: python .github/workflows/verify_result.py -c ${{ matrix.config }}
    - if: ${{ matrix.os == 'windows-latest' }}
      name: Setup config (using SAMPLE-config.py as config.py) - WINDOWS
      run: python .github\workflows\verify_result.py -c ${{ matrix.config }}
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: RUNNING TEST - LINUX
      run: |
         python default.py -t ${{ matrix.version }} -r -u https://webperf.se/ -o .github/workflows/testresult-${{ matrix.version }}.json
         python .github/workflows/verify_result.py -t ${{ matrix.version }}
    - if: ${{ matrix.os == 'windows-latest' }}
      name: RUNNING TEST - WINDOWS
      run: |
         python default.py -t ${{ matrix.version }} -r -u https://webperf.se/ -o .github\workflows\testresult-${{ matrix.version }}.json
         python .\.github\workflows\verify_result.py -t ${{ matrix.version }}
