name: "Regression Test - HTTP & Network Test"
on:
  schedule:
    - cron: "30 19 * * *"
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [windows-latest]
                config: ['REVIEW_SHOW_IMPROVEMENTS_ONLY=False,SITESPEED_USE_DOCKER=False,CSP_ONLY=True,USE_DETAILED_REPORT=True']
                version: [21]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
    - name: Setup Node.js (v4 version 20.x)
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Setup Sitespeed.io npm package (ONLY used for Sitespeed)
      run: npm install sitespeed.io
    - if: ${{ matrix.os == 'windows-latest' }}
      name: Setup config (using SAMPLE-config.py as config.py) - WINDOWS
      run: python .github\workflows\verify_result.py -c ${{ matrix.config }}
    - if: ${{ matrix.os == 'windows-latest' }}
      name: RUNNING TEST - WINDOWS
      run: |
         python default.py -t ${{ matrix.version }} -r -u https://www.eskilstuna.se/ -o .github\workflows\testresult-${{ matrix.version }}.json
         python .github\workflows\verify_result.py -t ${{ matrix.version }}
